Update Finance.java - added year property
KuliginStepan/dadata-client pull request #27
Opened 2021-05-12 12:15 UTC by Strong-Wings

Добавлен год в Finance.java, в соответствии с документацией
![Screenshot](https://user-images.githubusercontent.com/37307239/117973317-ea916300-b334-11eb-9298-09fd0b91e03e.jpg)

2021-05-12 15:01 UTC, KuliginStepan commented on src/main/java/com/kuliginstepan/dadata/client/domain/organization/Finance.java
> +    String year;
Почему решили использовать `String` вместо `Integer`?

2021-05-12 15:04 UTC, Strong-Wings commented on src/main/java/com/kuliginstepan/dadata/client/domain/organization/Finance.java
> +    String year;
Не нашёл ни одной организации, у которой задан год, поэтому не знаю точно в каком формате он бывает. String как универсальное решение

2021-05-12 15:47 UTC, KuliginStepan requested changes

2021-05-12 15:47 UTC, KuliginStepan commented on src/main/java/com/kuliginstepan/dadata/client/domain/organization/Finance.java
> +    String year;
Вот тут в документации есть типы данных https://confluence.hflabs.ru/pages/viewpage.action?pageId=204669126
Судя по ней, год является `int`. Я бы предложил сделать аналогично и использовать `Integer`

2021-05-12 15:51 UTC, Strong-Wings commented on src/main/java/com/kuliginstepan/dadata/client/domain/organization/Finance.java
> +    String year;
Вижу, спасибо! Поменял на Integer

2021-05-13 04:00 UTC, KuliginStepan approved these changes

2021-05-13 05:39 UTC, merged