Add parameter to configure the byte buffer size
KuliginStepan/dadata-client pull request #28
Opened 2021-06-17 04:28 UTC by vprilepskiy

Добавление параметра максимального разрешенного размера байтового буфера для исправления ошибки возникающей в результате превышения размера заданного по умолчанию в 256 Кбайт при получении ответа от DaData. (Exceeded limit on max bytes to buffer : 262144)
Опытным путем, по нескольким крупным организациям, был получен размер ответа ~300 Кбайт
Установил значение по умолчанию в 512 Кбайт и вынес настройку наружу.

2021-06-22 21:21 UTC, KuliginStepan requested changes

2021-06-22 21:21 UTC, KuliginStepan commented on src/main/java/com/kuliginstepan/dadata/client/DadataClientBuilder.java
> +    private Integer maxInMemorySize;
Я бы использовал вместо `Integer` тип `DataSize`, потому что сам спринг его использует и для пользователей проще конфигурировать будет.

2021-06-23 03:55 UTC, vprilepskiy commented on src/main/java/com/kuliginstepan/dadata/client/DadataClientBuilder.java
> +    private Integer maxInMemorySize;
Заменил тип Integer на тип DataSize.

2021-06-23 05:40 UTC, KuliginStepan approved these changes
Все отлично, спасибо за PR! Сегодня сделаю релиз новой версии.

2021-06-23 05:40 UTC, merged

2021-06-24 10:11 UTC, vprilepskiy commented
Спасибо тебе! Ждём версию.