Поддержка соединений с Dadata через прокси-сервер
KuliginStepan/dadata-client pull request #30
Opened 2021-07-24 14:30 UTC by lbreeze

+ мелкий рефакторинг, тесты, описание

2021-07-31 11:45 UTC, KuliginStepan requested changes

2021-07-31 11:45 UTC, KuliginStepan commented on src/main/java/com/kuliginstepan/dadata/client/DadataClientProperties.java
> +    private ProxyProvider.Proxy proxyType = ProxyProvider.Proxy.HTTP;
Предлагаю выделить все настройки прокси в отдельный класс и использовать его. Например, выделить класс `ProxyProperties` и в нем `type`, `server`, `port` – и дальше добавить валидацию на эти поля через `@NotNull` и `@NotEmpty`. Чтобы валидация заработала, нужно дополнительно добавить `@Validated` над классом `DadataClientProperties` и `@Valid` над полем `ProxyProperties proxy` в классе `DadataClientProperties`. 

Валидация позволит убрать 3 проверки на `null` и заменить их одной проверкой.

2021-08-04 06:03 UTC, lbreeze commented on src/main/java/com/kuliginstepan/dadata/client/DadataClientProperties.java
> +    private ProxyProvider.Proxy proxyType = ProxyProvider.Proxy.HTTP;
Думал раньше есть ли смысл выделения группы настроек в подкласс - переделал. Для того, чтобы валидация заработала - нужно помимо этого добавлять зависимость от `javax.validation:validation-api`, а также ее реализацию (здесь она не используется, например при проверке токена). В пользовательских проектах при использовании этой библиотеки может быть своя реализация или не быть вообще. Не считаю это целесообразным, но идея здравая - добавил валидацию средствами lombok через `@NonNull`

2021-08-15 18:46 UTC, KuliginStepan reviewed
Спасибо за PR! В ближайшее время сделаю релиз.

2021-08-15 18:46 UTC, merged